#!/usr/bin/env python3
"""Embeds a compiled SPIR-V binary into a C++17 header.

Used by Vortyx Phase 3 to ship the pre-compiled vector-addition compute
shader inside vortyx_core, so building the project never requires the
Vulkan SDK and nothing is downloaded at runtime.

Usage:
    python3 scripts/embed_spv.py <input.spv> <output.hpp> <variable_basename>
"""

import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 1

    spv_path, out_path, base_name = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(spv_path, "rb") as f:
        data = f.read()

    # Basic SPIR-V sanity: magic number 0x07230203 (little endian).
    if len(data) < 20 or data[:4] != b"\x03\x02\x23\x07":
        print(f"ERROR: {spv_path} does not look like a SPIR-V binary")
        return 1

    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append(",".join(f"0x{b:02X}" for b in chunk))

    array_body = ",\n    ".join(lines)

    header = f"""#pragma once

// AUTO-GENERATED by scripts/embed_spv.py from {spv_path.rsplit("/", 1)[-1]}.
// Do not edit by hand. SPIR-V magic number verified (0x07230203).
// Source shader: shaders/vector_add.comp
// Regenerate:
//   glslangValidator -V --target-env vulkan1.0 shaders/vector_add.comp -o vector_add.spv
//   python3 scripts/embed_spv.py vector_add.spv src/core/compute/vector_add_spv.hpp vector_add

#include <cstddef>

namespace vortyx::compute::detail {{

inline constexpr unsigned char k{base_name}_spv[] = {{
    {array_body}
}};

inline constexpr std::size_t k{base_name}_spv_size = sizeof(k{base_name}_spv);

}}  // namespace vortyx::compute::detail
"""

    with open(out_path, "w") as f:
        f.write(header)

    print(f"embedded {len(data)} bytes of SPIR-V into {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
